#!/bin/bash

if ! command -v gnuplot &> /dev/null
then
    echo "To be able to use DAVIS at its full potential, you have to first install gnuplot."
    sudo apt-get update
    sudo apt-get install -y gnuplot
fi

make
./DAVIS.o

